### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by NinjaPerson24119** [cmput291-wi19-team29/Assignment3#10]
The file README.txt is a text file that lists the names and ccids (no student ids please) of all group members. This file must also include the names of anyone you collaborated with (as much as it is allowed within the course policy) or a line saying that you did not collaborate with anyone else. This is also the place to acknowledge the use of any source of information besides the course textbook and/or class notes.

**Comment by NinjaPerson24119** [comment]
Post your names and ccids here for easy reference. Also post external sources used here. I'll make the readme file once the rest of the project is complete.

**Comment by NinjaPerson24119** [comment]
Nicholas Wengel - ccid: wengel

**Comment by hughbagan** [comment]
Hugh Bagan - ccid: hbagan

**Comment by NinjaPerson24119** [comment]
This wasn't done in any specific PR, but it is done. Closing.
