### ISSUE TITLE
isInt function necessary?

### ISSUE THREAD

**Issue by aradu12** [cmput291-wi19-team29/Assignment3#13]
Is the `isInt()` function at the top of main.py needed? Instead of implementing our own function, why not just use `isinstance(var, int)`? Time complexity might be a little lighter this way, but it's not a huge deal. Thoughts?

**Comment by NinjaPerson24119** [comment]
The variable is a string so I have to call int() to convert it. A string is
not an instance of int. I'm checking the format of the string, not its type.

**Comment by aradu12** [comment]
oh i see, I was just confused by the name of the function

**Comment by NinjaPerson24119** [comment]
Yeah, technically it should be called isStringAnInt or something

**Comment by NinjaPerson24119** [comment]
I don't think the name is worth bothering to change, so closing
