### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by NinjaPerson24119** [cmput291-wi19-team29/Assignment3#8]
Program that tests all functionality for the terminal API. Could use bash or python.

**Comment by NinjaPerson24119** [comment]
@aradu12 @hughbagan do we actually want to make test cases, or just do it manually? The queries for this assignment aren't *that* complicated.

**Comment by aradu12** [comment]
Let's do it only if we have time?

**Comment by NinjaPerson24119** [comment]
Sounds good

**Comment by NinjaPerson24119** [comment]
I think it's safe to say that this isn't going to happen. Closing.
